version: 2.1

orbs:
  slack: circleci/slack@4.1
jobs:
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: checkout
          command: |
            ls -la
            echo ${CIRCLE_WORKFLOW_ID:0:7} 
workflows:
  default:
    jobs:
      - deploy-infrastructure
      